name: Release

on:
  push:
    branches: ['main']

jobs:
  lint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2

      - name: Install Dependencies
        run: npm ci

      - name: Run Lint
        run: npm run lint

  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2

      - name: Install Dependencies
        run: npm ci

      - name: Bump Version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: release
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2

      - name: Install Dependencies
        run: npm ci

      - name: Build Project
        run: npm run build --if-present

      - name: Deploy to Server
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: -rltgoDzvO --delete --exclude="cgi-bin/" --exclude=".htaccess" --exclude=".htpasswds" --exclude="docs/" --exclude=".well-known"
          path: dist/
          remote_path: ${{ secrets.SSH_DIR }}
          remote_host: ${{ secrets.SSH_HOST }}
          remote_user: ${{ secrets.SSH_USER }}
          remote_key: ${{ secrets.SSH_KEY }}