name: Staging

on:
  push:
    branches-ignore: ['main']

jobs:
  lint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2

      - name: Install Dependencies
        run: npm ci

      - name: Run Lint
        run: npm run lint

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2

      - name: Install Dependencies
        run: npm ci

      - name: Build Project
        run: npm run build --if-present

      - name: Deploy to Server
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: -rltgoDzvO --delete --exclude=".htaccess" --exclude=".well-known" --exclude=".htpasswds/" --exclude="cgi-bin/" --exclude="docs/"
          path: dist/
          remote_path: ${{ secrets.SSH_DEV_DIR }}
          remote_host: ${{ secrets.SSH_HOST }}
          remote_user: ${{ secrets.SSH_USER }}
          remote_key: ${{ secrets.SSH_KEY }}
